#! /usr/bin/python
# -*- coding: utf-8 -*-

#This file is part of RogueBox Adventures.
#
#    RogueBox Adventures is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    RogueBox Adventures is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with RogueBox Adventures.  If not, see <http://www.gnu.org/licenses/>.
 
texts ={'tutorial_1.1' : ('Welcome to the RogueBox Adventures', 
						'Tutorial!',
						'Lesson 1: Moving and interaction',
						'You can move your character by',
						'using [w,a,s,d]',
						'and interact with something by',
						'pressing [e]',
						'while standing on it.'),
		'tutorial_1.2' : ('You will find a guidepost in',
						'the south. Move there and read it!'),
		'info_soon' : ('Test Page',
						'Feature comming soon.'),
		'spear' : ('Spears',
					' ',
					'A spear is a weak melee weapon.'),
		'sword' : ('Swords',
					' ',
					'A sword is a medium melee weapon.'),
		'hammer' : ('Hammers',
					' ',
					'A hammer is a heavy melee weapon.'),
		'rune' : ('Runes',
					' ',
					'A rune is a very weak magical',
					'weapon.'),
		'wand' : ('Wands',
					' ',
					'A wand is a weak magical weapon.'),
		'rune staff' : ('Rune Staffs',
					' ',
					'A rune staff is a medium',
					'magical weapon.'),
		'artefact' : ('Artefacts',
					' ',
					'A artefact is a strong magical',
					'weapon.'),
		'helmet' : ('Helmets',
					' ',
					'A helmet can protect your head',
					'of physical damage.'),
		'armor' : ('Armors',
					' ',
					'A armor can protect your body',
					'of physical damage.'),
		'cuisse' : ('Cuisses',
					' ',
					'A cuisse can protect your legs',
					'of physical damage.'),
		'shoes' : ('Shoes',
					' ',
					'Shoes can protect your feet',
					'of physical damage.'),
		'axe' : ('Axes',
				' ',
				'A axe is a tool to chop',
				'down trees.'),
		'pickaxe'  : ('Pickaxes',
					' ',
					'A pickaxe is a tool to break',
					'rock.'),
		'ring' : ('Rings',
				' ',
				'A ring can increase your will.'),
		'amulet' : ('Amulets',
					' ',
					'A amulet can increase your will.'),
		'talisman' : ('Talismans',
					' ',
					'A talisman can increase your luck.'),
		'necklace' : ('Necklaces',
					' ',
					'A necklace can increase your luck.'),
		'decorative_clothes' : ('Decorative Clothes',
								' ',
								'This item changes the way you',
								'look like.'),
				}
